#
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile requirements.in
#
annotated-types==0.7.0
    # via pydantic
anyio==4.4.0
    # via httpx
atproto==0.0.61
    # via -r requirements.in
blinker==1.8.2
    # via flask
boto3==1.40.11
    # via -r requirements.in
botocore==1.40.11
    # via
    #   boto3
    #   s3transfer
certifi==2024.8.30
    # via
    #   httpcore
    #   httpx
cffi==1.17.1
    # via cryptography
click==8.1.7
    # via
    #   atproto
    #   flask
cryptography==42.0.8
    # via atproto
dnspython==2.6.1
    # via atproto
exceptiongroup==1.3.0
    # via anyio
flask==3.0.2
    # via -r requirements.in
h11==0.14.0
    # via httpcore
httpcore==1.0.5
    # via httpx
httpx==0.26.0
    # via atproto
idna==3.8
    # via
    #   anyio
    #   httpx
itsdangerous==2.2.0
    # via flask
jinja2==3.1.4
    # via flask
jmespath==1.0.1
    # via
    #   boto3
    #   botocore
libipld==3.1.1
    # via atproto
markupsafe==2.1.5
    # via
    #   jinja2
    #   werkzeug
memory-profiler==0.61.0
    # via -r requirements.in
numpy==1.26.4
    # via
    #   -r requirements.in
    #   pandas
pandas==2.2.2
    # via -r requirements.in
psutil==6.0.0
    # via memory-profiler
pycparser==2.22
    # via cffi
pydantic==2.7.4
    # via
    #   -r requirements.in
    #   atproto
pydantic-core==2.18.4
    # via pydantic
python-dateutil==2.9.0.post0
    # via
    #   botocore
    #   pandas
python-dotenv==1.0.1
    # via -r requirements.in
pytz==2024.1
    # via pandas
s3transfer==0.13.1
    # via boto3
six==1.16.0
    # via python-dateutil
sniffio==1.3.1
    # via
    #   anyio
    #   httpx
typing-extensions==4.12.2
    # via
    #   -r requirements.in
    #   anyio
    #   atproto
    #   exceptiongroup
    #   pydantic
    #   pydantic-core
tzdata==2024.1
    # via pandas
urllib3==1.26.19
    # via
    #   -r requirements.in
    #   botocore
websockets==12.0
    # via atproto
werkzeug==3.0.4
    # via flask
